"""empty message

Revision ID: 366205b1362c
Revises: 16b4a14775cf
Create Date: 2020-09-25 00:02:14.177863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '366205b1362c'
down_revision = '16b4a14775cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
    op.execute('UPDATE todos SET completed = FALSE WHERE COMPLETED IS NULL;')
    op.alter_column('todos','completed',nullable=False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
